import java.io.*;
import java.nio.file.*;
import java.util.Base64;

/**
 * Build-time tool: reads a binary file and writes out a .java source file
 * that embeds it as base64 string constants, decodable at runtime.
 *
 * This is the same job a code-generation step would do in any project that
 * needs to bundle a native binary reliably with Ant/NetBeans: build tools
 * like this typically emit a similar generated source file.
 *
 * Usage: java GenerateEmbedded <inputBinary> <outputJavaFile>
 *
 * Why chunk into multiple strings at all (even here)?
 *   - A single Java string constant's UTF-8 form can't exceed 65535 bytes
 *     (a .class file format limit).
 *   - A real native launcher binary can easily be 250-350KB, so its base64
 *     needs several ~57600-char chunks to stay under that ceiling.
 *   - This demo binary is tiny, so it normally fits in ONE chunk -- but the
 *     chunking code below still runs unconditionally, so this same tool
 *     would keep working unmodified if you swap in a much bigger real stub.
 */
public class GenerateEmbedded {

    private static final int CHUNK_SIZE = 50_000; // stay safely under 65535 bytes/string

    public static void main(String[] args) throws IOException {
        if (args.length != 2) {
            System.err.println("Usage: java GenerateEmbedded <inputBinary> <outputJavaFile>");
            System.exit(1);
        }
        File input = new File(args[0]);
        File output = new File(args[1]);

        byte[] bytes = Files.readAllBytes(input.toPath());
        String b64 = Base64.getEncoder().encodeToString(bytes);
        int total = b64.length();
        int chunkCount = (int) Math.ceil(total / (double) CHUNK_SIZE);

        try (PrintWriter w = new PrintWriter(new FileWriter(output))) {
            w.println("import java.util.Base64;");
            w.println();
            w.println("/** GENERATED by GenerateEmbedded.java from " + input.getName()
                    + " (" + bytes.length + " bytes). Do not edit by hand. */");
            w.println("public final class EmbeddedStub {");
            w.println();
            w.println("    private EmbeddedStub() {}");
            w.println();
            w.println("    public static byte[] bytes() {");
            w.println("        StringBuilder sb = new StringBuilder();");
            w.println("        for (String chunk : CHUNKS) sb.append(chunk);");
            w.println("        return Base64.getDecoder().decode(sb.toString());");
            w.println("    }");
            w.println();
            w.print("    private static final String[] CHUNKS = {");
            for (int i = 0, n = 0; i < total; i += CHUNK_SIZE, n++) {
                int end = Math.min(i + CHUNK_SIZE, total);
                w.println();
                w.print("        \"" + b64.substring(i, end) + "\"");
                w.print(n < chunkCount - 1 ? "," : "");
            }
            w.println();
            w.println("    };");
            w.println("}");
        }

        System.out.println("Wrote " + output + " (" + bytes.length + " source bytes -> "
                + b64.length() + " base64 chars -> " + chunkCount + " chunk(s))");
    }
}
